emeals/urls.py
"""emeals URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    include,
    path
)

# View
from emeals import views as emeals_views

urlpatterns = [
    path('users/', include(('users.urls', 'users'), namespace='users')),

    path('dishes/', include(('dishes.urls', 'dishes'), namespace='dishes')),

    path('menus/', include(('menus.urls', 'menus'), namespace='menus')),

    path('reservations/', include(('reservations.urls', 'reservations'), namespace='reservations')),

    path(
      route='',
      view=emeals_views.home_view,
      name='emeals_home'
    ),
    path(
      route='404',
      view=emeals_views.not_found_view,
      name='not_found'
    ),
    path(
      route='500',
      view=emeals_views.server_error_view,
      name='server_error'
    )

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menus/urls.py
"""Menus URLs."""

# Django
from django.urls import path

# View
from menus import views as menu_views

urlpatterns = [
    path(route='', view=menu_views.list_view, name='menu_list'),

    path(route='create/', view=menu_views.create_view, name='menu_create'),

    path(route='<uuid:menu_id>/confirm', view=menu_views.confirm_view, name='menu_confirm'),

    path(route='<uuid:menu_id>/notify', view=menu_views.menu_notify, name='menu_notify' ),

    path(route='check-today-menu/', view=menu_views.check_menu_of_day, name="check_menu_of_day"),

    path(route='not-available/', view=menu_views.not_available_view, name="not_available"),

    path(route='<uuid:menu_id>/dishes/edit/', view=menu_views.edit_dishes_view, name='menu_edit_dishes'),

    path(
        route='<uuid:menu_id>/dishes/<uuid:dish_id>/add/',
        view=menu_views.add_dishes_view,
        name='menu_add_dishes'
    ),

    path(
        route='<uuid:menu_id>/dishes/<uuid:menu_dish_id>/remove/',
        view=menu_views.remove_dishes_view,
        name='menu_remove_dishes'
    ),

    path(route='<uuid:menu_id>', view=menu_views.menu_of_day, name='menu_of_day')
]

reservations/urls.py
"""Reservations URLs."""

# Django
from django.urls import path

# View
from reservations import views as reservation_views

urlpatterns = [
    path(
        route='',
        view=reservation_views.list_view,
        name='menu_list'
    ),
    path(
        route='<uuid:menu_dish_id>/reservate',
        view=reservation_views.reserve_view,
        name='menu_reserve'
    ),
]

menus/models.py
"""Menus model."""

import uuid

# Django
from django.db import models
from django.utils import timezone

from emeals.settings import RESERVE_CLOSING


class Menu(models.Model):
    """Menus model."""
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateTimeField(
        default=timezone.now,
        null=False,
        help_text='Date the menu will be available.'
    )
    name = models.TextField(
        max_length=50,
        blank=False,
        default="today's menu",
        help_text='Descriptive name.'
    )
    is_confirmed = models.BooleanField(
        'confirmed by seller/Nora',
        default=False,
        help_text=(
            'Help easily distinguish status of Menú, False could allow modifications.'
        )
    )
    created_at = models.DateTimeField(
        default=timezone.now,
        editable=False,
        null=False,
        blank=False,
        help_text='Date time on which the object was created.'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        null=True,
        blank=True,
        help_text='Date time on which the object was last modified.'
    )

    class Meta:
        """Meta option."""
        get_latest_by = 'created_at'
        ordering = ['-created_at', '-updated_at']

    def __str__(self):
        """Return name."""
        return self.name

    def is_available_today(self):
        """Check if the menu is available today."""
        today = timezone.localtime().strftime('%Y-%m-%d')
        current_hour = timezone.localtime().strftime('%H')
        return self.date.strftime('%Y-%m-%d') == today and current_hour < RESERVE_CLOSING


class MenuDishes(models.Model):
    """Menus Dishes model."""
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    menu = models.ForeignKey('menus.Menu', on_delete=models.CASCADE)
    dish = models.ForeignKey('dishes.Dish', on_delete=models.CASCADE)

    class Meta:
        unique_together = (('menu', 'dish'),)

    def __str__(self):
        """Return menu_id."""
        return '{} - {}: ${}'.format(
            self.menu.name,
            self.dish.description,
            self.dish.price
        )

menus/forms.py
"""Menu forms."""

from datetime import datetime

# Django
from django import forms
from django.utils import timezone

# Models
from menus.models import Menu


class MenuForm(forms.Form):
    """Menu Form."""

    date = forms.DateField(
        label='Date of Menu:',
        initial=datetime.today,
        required=True
    )
    name = forms.CharField(
        label='Monday day menu!',
        max_length=150,
        min_length=4,
        required=True
    )

    def clean_date(self):
        """
        Model validations by date field

        A menu cannot be added under a date that is already registered for
        another, and menus cannot be added for dates before the current day.
        """
        creation_date = self.cleaned_data['date']
        menu_taken = Menu.objects.filter(date=creation_date).exists()
        today = timezone.localtime().strftime('%Y-%m-%d')
        if menu_taken:
            raise forms.ValidationError('A menu for the selected date already exists, please select a new one.')
        if creation_date.strftime('%Y-%m-%d') < today:
            raise forms.ValidationError('You cannot select a date before today.')

        return creation_date

menus/views.py
"""Menus views."""

# Django
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Models
from menus.models import Menu, MenuDishes
from dishes.models import Dish

# Forms
from .forms import MenuForm

# Celery
from emeals.celery import send_menus


@login_required
def list_view(request):
    """
    Get a list of all registered menus.
    """
    menus = Menu.objects.all()
    return render(request, 'menus/list.html', context={
        'menus': menus
    })


@login_required
def create_view(request):
    """
    Create a new menu

    A new menu will be generated given a particular date, if for the selected
    date a menu already exists, it will be canceled and the user will be notified
    that he cannot add another menu for the same date.
    """
    form = MenuForm()
    if request.method == 'POST':
        form = MenuForm(request.POST)
        if form.is_valid():
            menu = Menu(**form.cleaned_data)
            menu.save()

            return HttpResponseRedirect(reverse('menus:menu_edit_dishes', args=(
                menu.uuid,
            )))

    return render(request, 'menus/create.html', context={
        'form': form
    })


@login_required
def add_dishes_view(request, menu_id, dish_id):
    """
    It allows us to add the different dishes that make up the menu.
    """
    menu = Menu.objects.get(pk=menu_id)
    dish = Dish.objects.get(pk=dish_id)

    menu_dishes_taken = MenuDishes.objects.filter(
        menu_id=menu.uuid,
        dish_id=dish.uuid
    ).exists()

    if not menu_dishes_taken:
        menu_dishes = MenuDishes(menu=menu, dish=dish)
        menu_dishes.save()

    return HttpResponseRedirect(reverse('menus:menu_edit_dishes', args=(
        menu.uuid,
    )))


@login_required
def edit_dishes_view(request, menu_id):
    """
    Allows us to edit the different dishes that make up the menu.
    """
    menu = Menu.objects.get(pk=menu_id)
    my_menu_dishes = MenuDishes.objects.filter(menu_id=menu_id)
    ids_dishes_list = []
    for my_md in my_menu_dishes:
        ids_dishes_list.append(my_md.dish.uuid)

    dishes = Dish.objects.all()

    return render(request, 'menus/edit_dishes.html', context={
        'menu': menu,
        'dishes': dishes,
        'my_menu_dishes': my_menu_dishes,
        'ids_dishes_list': ids_dishes_list
    })


@login_required
def remove_dishes_view(request, menu_id, menu_dish_id):
    """
    It allows us to remove a dish from a respective menu,
    as long as the menu has not been confirmed.
    """
    menu = Menu.objects.get(pk=menu_id)
    menu_dish = MenuDishes.objects.get(pk=menu_dish_id)

    if menu.is_confirmed:
        msg = 'We are sorry, but this menu: {} has already been confirmed, '
        msg += 'therefore you can no longer edit your dishes.'.format(menu.name)
        messages.info(request, msg)
    else:
        menu_dish.delete()

    return HttpResponseRedirect(reverse('menus:menu_edit_dishes', args=(
        menu.uuid,
    )))


def check_menu_of_day(request):
    """
    Method that is responsible for verifying if there is
    a menu available to be offered to users
    """
    try:
        menu = Menu.objects.latest('date')
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('not_found'))

    if not menu.is_available_today:
        return HttpResponseRedirect(reverse('menus:not_available'))

    return HttpResponseRedirect(reverse('menus:menu_of_day', args=(
        menu.uuid,
    )))


def menu_of_day(request, menu_id):
    """List menu of day."""
    try:
        menu = Menu.objects.get(pk=menu_id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('not_found'))

    if menu.is_available_today:
        menu_dishes = MenuDishes.objects.all().filter(menu_id=menu_id)
        return render(request, 'menus/menu_of_day.html', context={
            'menu_dishes': menu_dishes
        })

    return HttpResponseRedirect(reverse('menus:not_available'))


def not_available_view(request):
    """Menu not available."""
    return render(request, 'menus/not_available.html')


@login_required
def confirm_view(request, menu_id):
    """
    Confirm menu status

    The menu will be available as long as it is confirmed by the admin / seller / Nora user,
    once confirmed it can no longer be modified
    """
    try:
        menu = Menu.objects.get(pk=menu_id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('not_found'))

    if not menu.is_confirmed:
        menu_dishes_taken = MenuDishes.objects.filter(menu_id=menu.uuid).exists()

        if not menu_dishes_taken:
            return HttpResponseRedirect(reverse('menus:menu_edit_dishes', args=(
                menu.uuid,
            )))

        menu.is_confirmed = True
        menu.save()

    return HttpResponseRedirect(reverse('menus:menu_list'))


@login_required
def menu_notify(request, menu_id):
    """
    Notify menu

    View that allows you to manually notify the menu of the day
    in case it is necessary to do it in addition to the periodic task.
    """
    try:
        menu = Menu.objects.get(pk=menu_id)
        if menu.is_available_today:
            send_menus.delay()
            msg = 'A notification will be sent to the slack channel for the {} menu'.format(menu.name)
            messages.info(
                request,
                msg
            )
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('not_found'))

    return HttpResponseRedirect(reverse('menus:menu_list'))

templates/menus/create.html
{% extends "base.html" %}
{% block head_content %}
	<title>Menus | EMeals</title>
{% endblock %}
{% block container %}
<div class="row">
	<div class="col-lg-2 ml-auto">
		<a href="{% url 'menus:menu_list' %}" class="btn btn-secondary btn-block">go list</a>
	</div>
	<div class="col-lg-12">
		<form method="POST" action="{% url 'menus:menu_create' %}">
			{% csrf_token %}
			<div class="row">
				<div class="col-lg-6">
					<div class="form-group">
						<label for="dateMenu">{{ form.date.label }}</label>
						<input type="date" name="date"
							class="form-control {% if form.date.errors %}is-invalid{% endif %}"
							id="date-menu"
							placeholder="Enter a date"
                               value="{% if form.date.value is not None %}{{ form.date.value }}{% endif %}">
						<div class="invalid-feedback">
							{% for error in form.date.errors %}
								{{ error }}
							{% endfor %}
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="form-group">
						<label for="menuName">Menu name:</label>
						<input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                               id="menu-name" placeholder="{{ form.date.label }}"
                               value="{% if form.name.value is not None %}{{ form.name.value }}{% endif %}" name="name">
						<div class="invalid-feedback">
							{% for error in form.name.errors %}
								{{ error }}
							{% endfor %}
						</div>
					</div>
				</div>
				<div class="col-lg-2 ml-auto">
			    	<button type="submit" class="btn btn-block btn-primary">Save</button>
			    </div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

templates/menus/edit_dishes.html
{% extends "base.html" %}
{% block head_content %}
	<title>Menus | EMeals</title>
{% endblock %}
{% block container %}
    <div class="row">
        <div class="col-lg-2 ml-auto">
            <a href="{% url 'menus:menu_list' %}" class="btn btn-secondary btn-block">go list</a>
        </div>
        <div class="col-lg-12">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                         <div class="alert alert-info {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-12">
                    <h3>Available dishes to select</h3>
                    <ul class="list-group">
                        {% for dish in dishes %}
                            {% if dish.uuid not in ids_dishes_list %}
                                 <li class="list-group-item">
                                    {{ dish.description }}
                                    <a href="{% url 'menus:menu_add_dishes' menu_id=menu.uuid dish_id=dish.uuid %}"
                                       class="btn btn-primary btn-sm float-right">
                                        Add dish
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-12 mt-5">
                    <h3>{{ menu.name }}</h3>
                    <ul class="list-group">
                        {% for my_menu_dish in my_menu_dishes %}
                            <li class="list-group-item">
                                {{  my_menu_dish.dish.description }}
                                <a href="{% url 'menus:menu_remove_dishes' menu_id=menu.uuid menu_dish_id=my_menu_dish.uuid  %}"
                                   class="btn btn-danger btn-sm float-right">Remove dish
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/menus/list.html
{% extends "base.html" %}
{% block head_content %}
	<title>Menus | EMeals</title>
{% endblock %}
{% block container %}
	<div class="row">
		<div class="col-lg-2 ml-auto mb-3">
			<a href="{% url 'menus:menu_create' %}" class="btn btn-block btn-primary">
				Add new
			</a>
		</div>
    <div class="col-lg-12">
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                     <div class="alert alert-info {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
		<div class="col-lg-12">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th scope="col">Menu name</th>
						<th scope="col">Menu date</th>
                        <th scope="col">Is confirmed</th>
						<th scope="col" width="200"></th>
					</tr>
				</thead>
				<tbody>
					{% for menu in menus %}
						<tr>
							<td>{{ menu.name }}</td>
							<td>{{ menu.date|date:"d M Y" }}</td>
                            <td>
                                {% if not menu.is_confirmed %}
                                    <span class="badge badge-pill badge-warning">Unconfirmed</span>
                                {% else %}
                                    <span class="badge badge-pill badge-success">Confirmed</span>
								{% endif %}
                            </td>
							<td>
                                {% if not menu.is_confirmed %}
                                    <a href="{% url 'menus:menu_confirm' menu_id=menu.uuid %}"
                                       class="btn btn-sm btn-primary">
                                        Confirm
                                    </a>&nbsp;&nbsp;
                                    <a href="{% url 'menus:menu_edit_dishes' menu_id=menu.uuid %}"
                                       class="btn btn-sm btn-secondary">
                                        Edit Menu
                                    </a>
								{% endif %}
                            {% if menu.is_available_today %}
                                <a href="{% url 'menus:menu_notify'  menu_id=menu.uuid %}"
                                   class="btn btn-outline-primary btn-sm">
                                    notify menu
                                </a>
                            {% endif %}
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}

templates/menus/menu_of_day.html
{% extends "base_public.html" %}
{% block head_content %}
	<title>Menus of Day| EMeals</title>
{% endblock %}
{% block container %}
    <div class="row justify-content-md-center">
        <div class="col-lg-7">
            <h1>Menu of day</h1>
            <div class="list-group">
                {% for menu_dishe in menu_dishes %}
                    <li class="list-group-item">
                        {{ menu_dishe.dish.description | title }}
                        <a href="{% url 'reservations:menu_reserve' menu_dish_id=menu_dishe.uuid %}"
                           class="btn btn-sm btn-dark float-right">
                            Reserve
                        </a>
                    </li>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/menus/not_available.html
{% extends "base_public.html" %}
{% block head_content %}
	<title>Menus of Day| EMeals</title>
{% endblock %}
{% block container %}
    <div class="row justify-content-md-center">
        <div class="col-lg-10 mt-5 text-center">
            <h2>The menu of the day is not available at the moment</h2>
            <a href="{% url 'reservations:menu_list' %}" class="btn btn-primary mt-3">
				Reservations
			</a>
        </div>
    </div>
{% endblock %}