dishes/urls.py
"""Dishes URLs."""

# View
from dishes import views as dishes_views

# Django
from django.urls import path

urlpatterns = [
    path(
        route='',
        view=dishes_views.list_view,
        name='dish_list'
    ),
    path(
        route='create/',
        view=dishes_views.create_view,
        name='dish_create'
    ),
]

emeals/urls.py
"""emeals URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    include,
    path
)

# View
from emeals import views as emeals_views

urlpatterns = [
    path('users/', include(('users.urls', 'users'), namespace='users')),

    path('dishes/', include(('dishes.urls', 'dishes'), namespace='dishes')),

    path('menus/', include(('menus.urls', 'menus'), namespace='menus')),

    path('reservations/', include(('reservations.urls', 'reservations'), namespace='reservations')),

    path(
      route='',
      view=emeals_views.home_view,
      name='emeals_home'
    ),
    path(
      route='404',
      view=emeals_views.not_found_view,
      name='not_found'
    ),
    path(
      route='500',
      view=emeals_views.server_error_view,
      name='server_error'
    )

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menus/urls.py
"""Menus URLs."""

# Django
from django.urls import path

# View
from menus import views as menu_views

urlpatterns = [
    path(route='', view=menu_views.list_view, name='menu_list'),

    path(route='create/', view=menu_views.create_view, name='menu_create'),

    path(route='<uuid:menu_id>/confirm', view=menu_views.confirm_view, name='menu_confirm'),

    path(route='<uuid:menu_id>/notify', view=menu_views.menu_notify, name='menu_notify' ),

    path(route='check-today-menu/', view=menu_views.check_menu_of_day, name="check_menu_of_day"),

    path(route='not-available/', view=menu_views.not_available_view, name="not_available"),

    path(route='<uuid:menu_id>/dishes/edit/', view=menu_views.edit_dishes_view, name='menu_edit_dishes'),

    path(
        route='<uuid:menu_id>/dishes/<uuid:dish_id>/add/',
        view=menu_views.add_dishes_view,
        name='menu_add_dishes'
    ),

    path(
        route='<uuid:menu_id>/dishes/<uuid:menu_dish_id>/remove/',
        view=menu_views.remove_dishes_view,
        name='menu_remove_dishes'
    ),

    path(route='<uuid:menu_id>', view=menu_views.menu_of_day, name='menu_of_day')
]

dishes/models.py
"""Dishes model."""

import uuid

# Django
from django.db import models
from django.utils import timezone


class Dish(models.Model):
    """Dishes model."""

    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    description = models.TextField(
        'Dish description__',
        null=False,
        help_text='Description of the elements that will be part of the dish'
    )
    price = models.PositiveIntegerField(default=0)
    is_enabled = models.BooleanField(
        'is enabled',
        default=True,
        help_text=(
            'Help to distinguish the dishes that are enabled from those that are not'
        )
    )
    created_at = models.DateTimeField(
        default=timezone.now,
        editable=False,
        null=False,
        blank=False,
        help_text='Date time on which the object was created.'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        null=True,
        blank=True,
        help_text='Date time on which the object was last modified.'
    )

    class Meta:
        """Meta option."""
        get_latest_by = 'created_at'
        ordering = ['-created_at', '-updated_at']

    def __str__(self):
        """Return description."""
        return self.description

dishes/forms.py
"""Dishe forms."""

# Models
# from dishes.models import Dishe

# Django
from django import forms


class DisheForm(forms.Form):
    """Dishe Form."""

    description = forms.CharField(
        label='Dishe description:',
        max_length=150,
        required=True
    )
    price = forms.IntegerField(
        label='Enter price',
        min_value=1,
        max_value=1000000,
        required=True
    )

dishes/views.py
"""Dishes views."""

from dishes.models import Dish

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import DisheForm


@login_required
def list_view(request):
    """Get a list of dishes."""

    dishes = Dish.objects.all()

    return render(request, 'dishes/list.html', {
        'dishes': dishes
    })


@login_required
def create_view(request):
    """Create a new dishe."""

    form = DisheForm()

    if request.method == 'POST':
        form = DisheForm(request.POST)
        if form.is_valid():
            new_dish = Dish(**form.cleaned_data)
            new_dish.save()

            return HttpResponseRedirect(reverse('dishes:dish_list'))

    return render(request, 'dishes/create.html', context={
        'form': form
    })

templates/dishes/create.html
{% extends "base.html" %}
{% block head_content %}
	<title>Dishes | EMeals</title>
{% endblock %}
{% block container %}
<div class="row">
	<div class="col-lg-2 ml-auto">
		<a href="{% url 'dishes:dish_list' %}" class="btn btn-secondary btn-block">go list</a>
	</div>
	<div class="col-lg-12">
		<form method="POST">
			{% csrf_token %}
			<div class="row">
				<div class="col-lg-12">
					<div class="form-group">
						<label for="dishe-descripion">{{ form.description.label }}</label>
						<textarea class="form-control {% if form.description.errors %}is-invalid{% endif %}" name="description"
						id="dishe-descripion" rows="2">{% if form.description.value is not None %}{{ form.description.value }}{% endif %}</textarea>

						<div class="invalid-feedback">
                            {% for error in form.description.errors %}{{ error }}{% endfor %}
                        </div>
					</div>
				</div>
				<div class="col-lg-3 mr-auto">
					<div class="form-group">
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text" id="price-element">$</span>
							</div>
							<input type="text" class="form-control {% if form.price.errors %}is-invalid{% endif %}" id="input-price" placeholder="{{ form.price.label }}" aria-describedby="price-element" name="price" value="{% if form.price.value is not None %}{{ form.price.value }}{% endif %}">
							<div class="invalid-feedback">
								{% for error in form.price.errors %}{{ error }}{% endfor %}
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-2 ml-auto">
			    	<button type="submit" class="btn btn-block btn-primary">Save</button>
			    </div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

templates/dishes/list.html
{% extends "base.html" %}
{% block head_content %}
	<title>Dishes | EMeals</title>
{% endblock %}
{% block container %}
	<div class="row">
		<div class="col-lg-2 ml-auto mb-3">
			<a href="{% url 'dishes:dish_create' %}" class="btn btn-block btn-primary">
				Add new
			</a>
		</div>
		<div class="col-lg-12">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th scope="col">Description</th>
						<th scope="col">Price</th>
					</tr>
				</thead>
				<tbody>
					{% for dishe in dishes %}
						<tr>
							<td>{{ dishe.description }}</td>
							<td>${{ dishe.price }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}